version: '3'
services:
  # Production service
  app:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped

  # Development service with hot-reload
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
